### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by Chrizzor84** [nikiedev/simple-php-pdo-database-class#2]
Hi, I'm trying to understand and learn php, pdo and oop'ing. But on testing this class, I'm getting an error:

`Fatal error: Uncaught Error: Call to a member function getAttribute() on null in C:\xampp2\htdocs\oly-app\includes\Db.class.php:218 Stack trace: #0 C:\xampp2\htdocs\oly-app\index.php(37): lib\Db->select('spelers', Array) #1 {main} thrown in C:\xampp2\htdocs\oly-app\includes\Db.class.php on line 218`

The code on line 37 is:
`$player = $db->select('players', ['id' => 4]); `

**Comment by nikiedev** [comment]
Well, as I see the problem is with the namespace. Try to name it due to yor directory structure, it is another that I did (read about the namespace in php at first).

**Comment by Chrizzor84** [comment]
Okay i took a clone of your project and its still giving me the same error.

Also, if I look in your usage.php, I see the the following code:
`$db->useDatabase('articles');`
which results in this error:
`Fatal error: Uncaught Error: Call to a member function prepare() on null in C:\xampp2\htdocs\pdotest\lib\Db.class.php:130 Stack trace: #0 C:\xampp2\htdocs\pdotest\index.php(10): lib\Db->useDatabase('players') #1 {main} thrown in C:\xampp2\htdocs\pdotest\lib\Db.class.php on line 130`

I tried reinstalling XAMPP but the problem stays the same

I'm new at the whole php and pdo world. But it looks like no data is stored in $dbh

**Comment by nikiedev** [comment]
I will check the class in my project till the end of week and write then. I hadn't the problem before. Thanks for issue.
